#!/bin/sh

# e.g. "sh aws-deploy.sh 0.0.1"

# create a file with AWS-related config:
# S3_BUCKET - S3 bucket name generated by AWS
. scripts/.hidden/aws-config

APP_NAME=follow-insider
VERSION=fi-source-$1
ENV_NAME=fi-eb-env
S3_ASSET=fi-web.jar

gradle build

aws s3 cp fi-web/build/libs/$S3_ASSET s3://"$S3_BUCKET"/

aws elasticbeanstalk create-application-version \
  --application-name $APP_NAME \
  --version-label "$VERSION" \
  --source-bundle S3Bucket="$S3_BUCKET",S3Key=$S3_ASSET

aws elasticbeanstalk update-environment \
  --application-name $APP_NAME \
  --environment-name $ENV_NAME \
  --version-label "$VERSION"
